name: APK AzurLane JMBQ Build Work
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: '区服名称-必须（必须是英文字母！例如 Bilibili，台服和外服请使用XAPK AzurLane JMBQ Build Work）'
        required: true
        type: string
        default: ''
      download_url:
        description: 'APK下载链接（只能填入直链，最好使用国外云盘的直链，例如Google云盘）'
        required: true
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 步骤1：检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 步骤2：设置 Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "18"
          distribution: "adopt"

      # 步骤3：设置 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      # 步骤4：安装 build-tools
      - name: Install build-tools
        run: |
          yes | sdkmanager --install "build-tools;35.0.0"
      
      # 步骤5：执行构建流程
      - name: Build APK
        run: |
          chmod +x merge_build.sh
          ./merge_build.sh "${{ github.event.inputs.server_name }}" "${{ github.event.inputs.download_url }}"
          
      # 步骤6：安装多线程下载工具 axel
      - name: Install dependencies
        run: sudo apt-get install axel -y
      
      # 步骤7：上传分卷测试文件
      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Azurlane-JMBQ-Test-Build
          path: |
            *.7z*
          retention-days: 3
